const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.plant = require("./plants.model")(mongoose);
db.category = require("./categories.model")(mongoose);
module.exports = db;